Name:           perl-Class-Std-Fast
Version:        0.0.8
Release:        1%{?dist}
Summary:        Faster but less secure than Class::Std
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Class-Std-Fast/
Source0:        http://www.cpan.org/authors/id/A/AC/ACID/Class-Std-Fast-v%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl-Class-Std >= 0.0.8
BuildRequires:  perl-Module-Build
BuildRequires:  perl-Scalar-List-Utils
BuildRequires:  perl-Test-Simple
#uildRequires:  perl(version)
Requires:       perl-Class-Std >= 0.0.8
Requires:       perl-Scalar-List-Utils
#equires:       perl(version)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Class::Std::Fast allows you to use the beautiful API of Class::Std in a
faster way than Class::Std does.

%prep
%setup -q -n Class-Std-Fast-v%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Jul 26 2012 Peter Briggs <peter.briggs@manchester.ac.uk> 0.0.8-1
- Specfile autogenerated by cpanspec 1.78.
