%global 	debug_package %{nil}
Name:		SOAPaligner-bin
Version:	2.21
Release:	1%{?dist}
Summary:	Alignment of short oligonucleotides onto reference sequences

Group:		Applications/Engineering
License:	Closed source
URL:		http://soap.genomics.org.cn/soapaligner.html
Source0:	http://soap.genomics.org.cn/down/soap2.21release.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

%description
SOAPaligner/soap2 is a program for faster and efficient alignment for short
oligonucleotide onto reference sequences. SOAPaligner/soap2 is compatible
with numerous applications, including single-read or pair-end resequencing.
The program features super fast and accurate alignment for huge amounts of
short reads generated by Illumina/Solexa Genome Analyzer.

This is a binary-only package.

%prep
%setup -q -n soap%{version}release


%build


%install
rm -rf %{buildroot}

mkdir -p %{buildroot}%{_bindir}
install -m 0755 soap %{buildroot}%{_bindir}
install -m 0755 2bwt-builder %{buildroot}%{_bindir}


%files
%defattr(-,root,root,-)
%doc soap.1 soap.man NOTE release
%{_bindir}/soap
%{_bindir}/2bwt-builder



%changelog
* Thu Mar 29 2012 Peter Briggs <peter.briggs@manchester.ac.uk> - 2.21-1
- initial version

